#let zds-documents = (
  (
    number: "0001",
    slug: "zds-process",
    title: "The Zaxon Discussion Process",
    state: "published",
    area: "documentation",
    category: "Process Memo",
    status: "Published",
    created: "2026-07-21",
    updated: "2026-07-21",
    summary: "Defines the ZDS lifecycle, numbering workflow, Typst project layout, registry, and bundle export for the paxos-zig monorepo.",
    source: "docs/zds/records/0001-zds-process.typ",
    html: "zds/0001-zds-process.html",
    pdf: "pdf/zds-0001-zds-process.pdf",
  ),
  (
    number: "0002",
    slug: "zaxonlite-product-plan",
    title: "Zaxonlite: Product and Delivery Plan",
    state: "published",
    area: "architecture",
    category: "Architectural Specification",
    status: "Published",
    created: "2026-07-19",
    updated: "2026-07-21",
    summary: "Specifies the embeddable Zaxonlite library and zaxon CLI: in-process SQLite replicated by paxos.ReplicatedLog, WAL/page-change replication in slot order, the journal-authoritative durability model, cluster roles (voters, witnesses, standbys, read replicas, gateways), the Paxos safety argument, rqlite/dqlite incorporation reviews, mandatory integration tests, verification gates, and the milestone delivery plan.",
    source: "docs/zds/records/0002-zaxonlite-product-plan.typ",
    html: "zds/0002-zaxonlite-product-plan.html",
    pdf: "pdf/zds-0002-zaxonlite-product-plan.pdf",
  ),
  (
    number: "0003",
    slug: "zaxonlite-security-remediation-plan",
    title: "Zaxonlite Security and Trust Plan",
    state: "committed",
    area: "security",
    category: "Security Assessment",
    status: "Remediated",
    created: "2026-07-21",
    updated: "2026-07-21",
    summary: "Documents the application-as-principal trust model, the supported deployment boundaries (embedded, Unix-domain socket, mTLS cluster), the revised risk register, the pre-remediation findings with their remediations, single-use token enrollment with locally generated CSRs, the encryption-at-rest deployment profile, the SQLite-style assurance strategy, the required security matrix, and release acceptance criteria.",
    source: "docs/zds/records/0003-zaxonlite-security-remediation-plan.typ",
    html: "zds/0003-zaxonlite-security-remediation-plan.html",
    pdf: "pdf/zds-0003-zaxonlite-security-remediation-plan.pdf",
  ),
  (
    number: "0004",
    slug: "zaxonlite-format",
    title: "Zaxonlite Format and Compatibility Contract",
    state: "committed",
    area: "architecture",
    category: "Format Contract",
    status: "Normative",
    created: "2026-07-20",
    updated: "2026-07-21",
    summary: "Freezes the first-release formats and is normative for upgrade checks: network protocol v6 framing with PSK/mTLS profiles and enrollment records, the transaction descriptor and ZXPL payload format, the epoch journal, identity/snapshot/current-pointer formats, release limits, and the operator upgrade and disaster-recovery procedures.",
    source: "docs/zds/records/0004-zaxonlite-format.typ",
    html: "zds/0004-zaxonlite-format.html",
    pdf: "pdf/zds-0004-zaxonlite-format.pdf",
  ),
  (
    number: "0005",
    slug: "zaxon-interactive-shell",
    title: "A Rich Interactive Shell for the zaxon CLI",
    state: "discussion",
    area: "cli",
    category: "Engineering Discussion",
    status: "Open for Discussion",
    created: "2026-07-21",
    updated: "2026-07-21",
    summary: "Plans the rich zaxon interactive shell on the libvaxis terminal library: grapheme-aware cursor line editing, ctrl+r incremental history search, comptime-driven dot-command dispatch and SQL keyword highlighting, width-aware colored tables with expanded and paged views, first-class Windows support, and the extraction of all CLI presentation code out of main.zig.",
    source: "docs/zds/records/0005-zaxon-interactive-shell.typ",
    html: "zds/0005-zaxon-interactive-shell.html",
    pdf: "pdf/zds-0005-zaxon-interactive-shell.pdf",
  ),
)
